/*
 * Pipedrive API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v2::models;
use serde::{Deserialize, Serialize};

/// ActivityItem1 : The activity object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityItem1 {
    /// The ID of the activity
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The subject of the activity
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    /// The type of the activity
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The ID of the user who owns the activity
    #[serde(rename = "owner_id", skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<i32>,
    /// The ID of the user who created the activity
    #[serde(rename = "creator_user_id", skip_serializing_if = "Option::is_none")]
    pub creator_user_id: Option<i32>,
    /// Whether the activity is deleted or not
    #[serde(rename = "is_deleted", skip_serializing_if = "Option::is_none")]
    pub is_deleted: Option<bool>,
    /// The creation date and time of the activity
    #[serde(rename = "add_time", skip_serializing_if = "Option::is_none")]
    pub add_time: Option<String>,
    /// The last updated date and time of the activity
    #[serde(rename = "update_time", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
    /// The ID of the deal linked to the activity
    #[serde(rename = "deal_id", skip_serializing_if = "Option::is_none")]
    pub deal_id: Option<i32>,
    /// The ID of the lead linked to the activity
    #[serde(rename = "lead_id", skip_serializing_if = "Option::is_none")]
    pub lead_id: Option<String>,
    /// The ID of the person linked to the activity
    #[serde(rename = "person_id", skip_serializing_if = "Option::is_none")]
    pub person_id: Option<i32>,
    /// The ID of the organization linked to the activity
    #[serde(rename = "org_id", skip_serializing_if = "Option::is_none")]
    pub org_id: Option<i32>,
    /// The ID of the project linked to the activity
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    /// The due date of the activity
    #[serde(rename = "due_date", skip_serializing_if = "Option::is_none")]
    pub due_date: Option<String>,
    /// The due time of the activity
    #[serde(rename = "due_time", skip_serializing_if = "Option::is_none")]
    pub due_time: Option<String>,
    /// The duration of the activity
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<String>,
    /// Whether the activity marks the assignee as busy or not in their calendar
    #[serde(rename = "busy", skip_serializing_if = "Option::is_none")]
    pub busy: Option<bool>,
    /// Whether the activity is marked as done or not
    #[serde(rename = "done", skip_serializing_if = "Option::is_none")]
    pub done: Option<bool>,
    /// The date and time when the activity was marked as done
    #[serde(rename = "marked_as_done_time", skip_serializing_if = "Option::is_none")]
    pub marked_as_done_time: Option<String>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Box<models::ActivityItemLocation>>,
    /// The participants of the activity
    #[serde(rename = "participants", skip_serializing_if = "Option::is_none")]
    pub participants: Option<Vec<models::ActivityItemParticipantsInner>>,
    /// The attendees of the activity
    #[serde(rename = "attendees", skip_serializing_if = "Option::is_none")]
    pub attendees: Option<Vec<models::ActivityItemAttendeesInner>>,
    /// The client used for the conference meeting
    #[serde(rename = "conference_meeting_client", skip_serializing_if = "Option::is_none")]
    pub conference_meeting_client: Option<String>,
    /// The URL of the conference meeting
    #[serde(rename = "conference_meeting_url", skip_serializing_if = "Option::is_none")]
    pub conference_meeting_url: Option<String>,
    /// The ID of the conference meeting
    #[serde(rename = "conference_meeting_id", skip_serializing_if = "Option::is_none")]
    pub conference_meeting_id: Option<String>,
    /// The public description of the activity
    #[serde(rename = "public_description", skip_serializing_if = "Option::is_none")]
    pub public_description: Option<String>,
    /// The priority of the activity. Mappable to a specific string using activityFields API.
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    /// The note of the activity
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

impl ActivityItem1 {
    /// The activity object
    pub fn new() -> ActivityItem1 {
        ActivityItem1 {
            id: None,
            subject: None,
            r#type: None,
            owner_id: None,
            creator_user_id: None,
            is_deleted: None,
            add_time: None,
            update_time: None,
            deal_id: None,
            lead_id: None,
            person_id: None,
            org_id: None,
            project_id: None,
            due_date: None,
            due_time: None,
            duration: None,
            busy: None,
            done: None,
            marked_as_done_time: None,
            location: None,
            participants: None,
            attendees: None,
            conference_meeting_client: None,
            conference_meeting_url: None,
            conference_meeting_id: None,
            public_description: None,
            priority: None,
            note: None,
        }
    }
}

