/*
 * Pipedrive API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FollowerChangelogItem {
    /// The type of change
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    /// The ID of the user who did the change
    #[serde(rename = "actor_user_id", skip_serializing_if = "Option::is_none")]
    pub actor_user_id: Option<i32>,
    /// The ID of the user who was following the entity
    #[serde(rename = "follower_user_id", skip_serializing_if = "Option::is_none")]
    pub follower_user_id: Option<i32>,
    /// The time at which the change happened
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl FollowerChangelogItem {
    pub fn new() -> FollowerChangelogItem {
        FollowerChangelogItem {
            action: None,
            actor_user_id: None,
            follower_user_id: None,
            time: None,
        }
    }
}

