/*
 * Pipedrive API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// FollowerItem1 : The follower object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FollowerItem1 {
    /// The ID of the user following the entity
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    /// The add time of the following
    #[serde(rename = "add_time", skip_serializing_if = "Option::is_none")]
    pub add_time: Option<String>,
}

impl FollowerItem1 {
    /// The follower object
    pub fn new() -> FollowerItem1 {
        FollowerItem1 {
            user_id: None,
            add_time: None,
        }
    }
}

