/*
 * Pipedrive API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v2::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetItemSearchResponseDataData {
    /// The array of found items
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::ItemSearchItem>>,
    /// The array of related items if `search_for_related_items` was enabled
    #[serde(rename = "related_items", skip_serializing_if = "Option::is_none")]
    pub related_items: Option<Vec<models::ItemSearchItem>>,
}

impl GetItemSearchResponseDataData {
    pub fn new() -> GetItemSearchResponseDataData {
        GetItemSearchResponseDataData {
            items: None,
            related_items: None,
        }
    }
}

