/*
 * Pipedrive API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProductSearchResponseAllOfDataItemsInnerItemOwner {
    /// The ID of the owner of the product
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
}

impl GetProductSearchResponseAllOfDataItemsInnerItemOwner {
    pub fn new() -> GetProductSearchResponseAllOfDataItemsInnerItemOwner {
        GetProductSearchResponseAllOfDataItemsInnerItemOwner {
            id: None,
        }
    }
}

