/*
 * Pipedrive API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v2::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFollowerChangelogsResponse {
    /// If the response is successful or not
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    /// Follower changelogs array
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::FollowerChangelogItem>>,
    #[serde(rename = "additional_data", skip_serializing_if = "Option::is_none")]
    pub additional_data: Option<Box<models::GetActivitiesResponseAllOfAdditionalData>>,
}

impl GetFollowerChangelogsResponse {
    pub fn new() -> GetFollowerChangelogsResponse {
        GetFollowerChangelogsResponse {
            success: None,
            data: None,
            additional_data: None,
        }
    }
}

