/*
 * Pipedrive API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPersonsResponseAllOfDataInnerImInner {
    /// The instant messaging account of the person
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// Whether the instant messaging account is primary or not
    #[serde(rename = "primary", skip_serializing_if = "Option::is_none")]
    pub primary: Option<bool>,
    /// The instant messaging account classification label
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl GetPersonsResponseAllOfDataInnerImInner {
    pub fn new() -> GetPersonsResponseAllOfDataInnerImInner {
        GetPersonsResponseAllOfDataInnerImInner {
            value: None,
            primary: None,
            label: None,
        }
    }
}

