/*
 * Pipedrive API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPipelinesResponseAllOfDataInner {
    /// The ID of the pipeline
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The name of the pipeline
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Defines the order of pipelines. The pipeline with the lowest `order_nr` is considered the default.
    #[serde(rename = "order_nr", skip_serializing_if = "Option::is_none")]
    pub order_nr: Option<i32>,
    /// Whether this pipeline is selected or not
    #[serde(rename = "is_selected", skip_serializing_if = "Option::is_none")]
    pub is_selected: Option<bool>,
    /// Whether this pipeline is marked as deleted or not
    #[serde(rename = "is_deleted", skip_serializing_if = "Option::is_none")]
    pub is_deleted: Option<bool>,
    /// Whether deal probability is disabled or enabled for this pipeline
    #[serde(rename = "is_deal_probability_enabled", skip_serializing_if = "Option::is_none")]
    pub is_deal_probability_enabled: Option<bool>,
    /// The pipeline creation time
    #[serde(rename = "add_time", skip_serializing_if = "Option::is_none")]
    pub add_time: Option<String>,
    /// The pipeline update time
    #[serde(rename = "update_time", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
}

impl GetPipelinesResponseAllOfDataInner {
    pub fn new() -> GetPipelinesResponseAllOfDataInner {
        GetPipelinesResponseAllOfDataInner {
            id: None,
            name: None,
            order_nr: None,
            is_selected: None,
            is_deleted: None,
            is_deal_probability_enabled: None,
            add_time: None,
            update_time: None,
        }
    }
}

