/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddActivityResponseAdditionalData {
    /// This field will be deprecated
    #[serde(rename = "updates_story_id", skip_serializing_if = "Option::is_none")]
    pub updates_story_id: Option<i32>,
}

impl AddActivityResponseAdditionalData {
    pub fn new() -> AddActivityResponseAdditionalData {
        AddActivityResponseAdditionalData {
            updates_story_id: None,
        }
    }
}

