/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteActivityTypesResponseAllOfData {
    /// The IDs of the deleted activity types
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<Vec<i32>>,
}

impl DeleteActivityTypesResponseAllOfData {
    pub fn new() -> DeleteActivityTypesResponseAllOfData {
        DeleteActivityTypesResponseAllOfData {
            id: None,
        }
    }
}

