/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

/// GetPipelineDealsMovementsStatisticsResponseAllOfDataMovementsBetweenStages : Movements between stages
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPipelineDealsMovementsStatisticsResponseAllOfDataMovementsBetweenStages {
    /// The count of the deals that have been moved between stages
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

impl GetPipelineDealsMovementsStatisticsResponseAllOfDataMovementsBetweenStages {
    /// Movements between stages
    pub fn new() -> GetPipelineDealsMovementsStatisticsResponseAllOfDataMovementsBetweenStages {
        GetPipelineDealsMovementsStatisticsResponseAllOfDataMovementsBetweenStages {
            count: None,
        }
    }
}

