/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDealUpdatesResponseAllOfDataInner {
    /// The type of the deal update. (Possible object types - dealChange, note, activity, mailMessage, invoice, document, file)
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// The creation date and time of the update
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    /// The data related to the update
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl GetDealUpdatesResponseAllOfDataInner {
    pub fn new() -> GetDealUpdatesResponseAllOfDataInner {
        GetDealUpdatesResponseAllOfDataInner {
            object: None,
            timestamp: None,
            data: None,
        }
    }
}

