/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAssociatedDealsResponseAllOfRelatedObjects {
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<Box<models::RelatedOrganizationDataWithActiveFlag>>,
    #[serde(rename = "person", skip_serializing_if = "Option::is_none")]
    pub person: Option<Box<models::AddActivityResponseRelatedObjectsPerson>>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::GetActivitiesResponseRelatedObjectsUser>>,
    #[serde(rename = "stage", skip_serializing_if = "Option::is_none")]
    pub stage: Option<Box<models::BaseStage>>,
    #[serde(rename = "pipeline", skip_serializing_if = "Option::is_none")]
    pub pipeline: Option<Box<models::BasePipeline>>,
}

impl GetAssociatedDealsResponseAllOfRelatedObjects {
    pub fn new() -> GetAssociatedDealsResponseAllOfRelatedObjects {
        GetAssociatedDealsResponseAllOfRelatedObjects {
            organization: None,
            person: None,
            user: None,
            stage: None,
            pipeline: None,
        }
    }
}

