/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDealResponseAdditionalData {
    /// The BCC email of the deal
    #[serde(rename = "dropbox_email", skip_serializing_if = "Option::is_none")]
    pub dropbox_email: Option<String>,
}

impl GetDealResponseAdditionalData {
    pub fn new() -> GetDealResponseAdditionalData {
        GetDealResponseAdditionalData {
            dropbox_email: None,
        }
    }
}

