/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

/// GetRolePipelinesResponseData : The response data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRolePipelinesResponseData {
    /// Either visible or hidden pipeline ids
    #[serde(rename = "pipeline_ids", skip_serializing_if = "Option::is_none")]
    pub pipeline_ids: Option<Vec<f64>>,
    /// Whether visible or hidden pipeline ids were returned
    #[serde(rename = "visible", skip_serializing_if = "Option::is_none")]
    pub visible: Option<bool>,
}

impl GetRolePipelinesResponseData {
    /// The response data
    pub fn new() -> GetRolePipelinesResponseData {
        GetRolePipelinesResponseData {
            pipeline_ids: None,
            visible: None,
        }
    }
}

