/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDealSearchResponseAllOfData {
    /// The array of deals
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::GetDealSearchResponseAllOfDataItemsInner>>,
}

impl GetDealSearchResponseAllOfData {
    pub fn new() -> GetDealSearchResponseAllOfData {
        GetDealSearchResponseAllOfData {
            items: None,
        }
    }
}

