/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAssociatedDealsResponse {
    /// If the response is successful or not
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    /// The array of deals
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::Deal>>,
    #[serde(rename = "additional_data", skip_serializing_if = "Option::is_none")]
    pub additional_data: Option<Box<models::FieldsResponseAllOfAdditionalData>>,
    #[serde(rename = "related_objects", skip_serializing_if = "Option::is_none")]
    pub related_objects: Option<Box<models::GetAssociatedDealsResponseAllOfRelatedObjects>>,
}

impl GetAssociatedDealsResponse {
    pub fn new() -> GetAssociatedDealsResponse {
        GetAssociatedDealsResponse {
            success: None,
            data: None,
            additional_data: None,
            related_objects: None,
        }
    }
}

