/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

/// GetPipelineDealsMovementsStatisticsResponseAllOfDataNewDealsFormattedValues : The formatted values of the deals
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPipelineDealsMovementsStatisticsResponseAllOfDataNewDealsFormattedValues {
    /// The formatted values of the deals
    #[serde(rename = "CURRENCY_ID", skip_serializing_if = "Option::is_none")]
    pub currency_id: Option<String>,
}

impl GetPipelineDealsMovementsStatisticsResponseAllOfDataNewDealsFormattedValues {
    /// The formatted values of the deals
    pub fn new() -> GetPipelineDealsMovementsStatisticsResponseAllOfDataNewDealsFormattedValues {
        GetPipelineDealsMovementsStatisticsResponseAllOfDataNewDealsFormattedValues {
            currency_id: None,
        }
    }
}

