/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDealResponse {
    /// If the response is successful or not
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::DealNonStrictWithDetails>>,
    #[serde(rename = "additional_data", skip_serializing_if = "Option::is_none")]
    pub additional_data: Option<Box<models::GetDealResponseAdditionalData>>,
    #[serde(rename = "related_objects", skip_serializing_if = "Option::is_none")]
    pub related_objects: Option<Box<models::GetDealResponseRelatedObjects>>,
}

impl GetDealResponse {
    pub fn new() -> GetDealResponse {
        GetDealResponse {
            success: None,
            data: None,
            additional_data: None,
            related_objects: None,
        }
    }
}

