/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

/// GoalAssignee : Who the goal is assigned to
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoalAssignee {
    /// The ID of the goal assignee
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The type of the assignee
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl GoalAssignee {
    /// Who the goal is assigned to
    pub fn new() -> GoalAssignee {
        GoalAssignee {
            id: None,
            r#type: None,
        }
    }
}

