/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Lead {
    /// The unique ID of the lead in the UUID format
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// The title of the lead
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The ID of the user who owns the lead
    #[serde(rename = "owner_id", skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<i32>,
    /// The ID of the user who created the lead
    #[serde(rename = "creator_id", skip_serializing_if = "Option::is_none")]
    pub creator_id: Option<i32>,
    /// The IDs of the lead labels which are associated with the lead
    #[serde(rename = "label_ids", skip_serializing_if = "Option::is_none")]
    pub label_ids: Option<Vec<uuid::Uuid>>,
    /// The ID of a person which this lead is linked to
    #[serde(rename = "person_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub person_id: Option<Option<i32>>,
    /// The ID of an organization which this lead is linked to
    #[serde(rename = "organization_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub organization_id: Option<Option<i32>>,
    /// Defines where the lead comes from. Will be `API` if the lead was created through the Public API and will be `Manually created` if the lead was created manually through the UI. 
    #[serde(rename = "source_name", skip_serializing_if = "Option::is_none")]
    pub source_name: Option<String>,
    /// The way this Lead was created. `origin` field is set by Pipedrive when Lead is created and cannot be changed.
    #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<String>,
    /// The optional ID to further distinguish the origin of the lead - e.g. Which API integration created this Lead.
    #[serde(rename = "origin_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub origin_id: Option<Option<String>>,
    /// The ID of your Marketing channel this Lead was created from. Recognized Marketing channels can be configured in your <a href=\"https://app.pipedrive.com/settings/fields\" target=\"_blank\" rel=\"noopener noreferrer\">Company settings</a>.
    #[serde(rename = "channel", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub channel: Option<Option<i32>>,
    /// The optional ID to further distinguish the Marketing channel.
    #[serde(rename = "channel_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<Option<String>>,
    /// A flag indicating whether the lead is archived or not
    #[serde(rename = "is_archived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<bool>,
    /// A flag indicating whether the lead was seen by someone in the Pipedrive UI
    #[serde(rename = "was_seen", skip_serializing_if = "Option::is_none")]
    pub was_seen: Option<bool>,
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<Box<models::LeadValue>>>,
    /// The date of when the deal which will be created from the lead is expected to be closed. In ISO 8601 format: YYYY-MM-DD.
    #[serde(rename = "expected_close_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expected_close_date: Option<Option<String>>,
    /// The ID of the next activity associated with the lead
    #[serde(rename = "next_activity_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next_activity_id: Option<Option<i32>>,
    /// The date and time of when the lead was created. In ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
    #[serde(rename = "add_time", skip_serializing_if = "Option::is_none")]
    pub add_time: Option<String>,
    /// The date and time of when the lead was last updated. In ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
    #[serde(rename = "update_time", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
    #[serde(rename = "visible_to", skip_serializing_if = "Option::is_none")]
    pub visible_to: Option<VisibleTo>,
    /// The BCC email of the lead
    #[serde(rename = "cc_email", skip_serializing_if = "Option::is_none")]
    pub cc_email: Option<String>,
}

impl Lead {
    pub fn new() -> Lead {
        Lead {
            id: None,
            title: None,
            owner_id: None,
            creator_id: None,
            label_ids: None,
            person_id: None,
            organization_id: None,
            source_name: None,
            origin: None,
            origin_id: None,
            channel: None,
            channel_id: None,
            is_archived: None,
            was_seen: None,
            value: None,
            expected_close_date: None,
            next_activity_id: None,
            add_time: None,
            update_time: None,
            visible_to: None,
            cc_email: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VisibleTo {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "3")]
    Variant3,
    #[serde(rename = "5")]
    Variant5,
    #[serde(rename = "7")]
    Variant7,
}

impl Default for VisibleTo {
    fn default() -> VisibleTo {
        Self::Variant1
    }
}

