/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

/// LeadValue : The potential value of the lead represented by a JSON object: `{ \"amount\": 200, \"currency\": \"EUR\" }`. Both amount and currency are required.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LeadValue {
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "currency")]
    pub currency: String,
}

impl LeadValue {
    /// The potential value of the lead represented by a JSON object: `{ \"amount\": 200, \"currency\": \"EUR\" }`. Both amount and currency are required.
    pub fn new(amount: f64, currency: String) -> LeadValue {
        LeadValue {
            amount,
            currency,
        }
    }
}

