/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

/// MailThreadAllOfParties : Parties of the mail thread
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailThreadAllOfParties {
    /// Recipients of the mail thread
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<Vec<models::MailThreadAllOfPartiesToInner>>,
    /// Senders of the mail thread
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<Vec<models::MailThreadAllOfPartiesToInner>>,
}

impl MailThreadAllOfParties {
    /// Parties of the mail thread
    pub fn new() -> MailThreadAllOfParties {
        MailThreadAllOfParties {
            to: None,
            from: None,
        }
    }
}

