/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

/// NoteProject : The project the note is attached to
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NoteProject {
    /// The title of the project the note is attached to
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl NoteProject {
    /// The project the note is attached to
    pub fn new() -> NoteProject {
        NoteProject {
            title: None,
        }
    }
}

