/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonDataWithIdAllOfEmailInner {
    /// The type of the email
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// The email of the associated person
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// Whether this is the primary email or not
    #[serde(rename = "primary", skip_serializing_if = "Option::is_none")]
    pub primary: Option<bool>,
}

impl PersonDataWithIdAllOfEmailInner {
    pub fn new() -> PersonDataWithIdAllOfEmailInner {
        PersonDataWithIdAllOfEmailInner {
            label: None,
            value: None,
            primary: None,
        }
    }
}

