/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::v1::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskResponseObject {
    /// The ID of the task, generated when the task was created
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The title of the task
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The ID of the project this task is associated with
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<f64>,
    /// The description of the task
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The ID of a parent task. Can not be ID of a task which is already a subtask.
    #[serde(rename = "parent_task_id", skip_serializing_if = "Option::is_none")]
    pub parent_task_id: Option<f64>,
    /// The ID of the user who will be the assignee of the task
    #[serde(rename = "assignee_id", skip_serializing_if = "Option::is_none")]
    pub assignee_id: Option<f64>,
    #[serde(rename = "done", skip_serializing_if = "Option::is_none")]
    pub done: Option<Done>,
    /// The due date of the task. Format: YYYY-MM-DD.
    #[serde(rename = "due_date", skip_serializing_if = "Option::is_none")]
    pub due_date: Option<String>,
    /// The creator of a task
    #[serde(rename = "creator_id", skip_serializing_if = "Option::is_none")]
    pub creator_id: Option<f64>,
    /// The creation date and time of the task in UTC. Format: YYYY-MM-DD HH:MM:SS.
    #[serde(rename = "add_time", skip_serializing_if = "Option::is_none")]
    pub add_time: Option<String>,
    /// The update date and time of the task in UTC. Format: YYYY-MM-DD HH:MM:SS.
    #[serde(rename = "update_time", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
    /// The marked as done date and time of the task in UTC. Format: YYYY-MM-DD HH:MM:SS.
    #[serde(rename = "marked_as_done_time", skip_serializing_if = "Option::is_none")]
    pub marked_as_done_time: Option<String>,
}

impl TaskResponseObject {
    pub fn new() -> TaskResponseObject {
        TaskResponseObject {
            id: None,
            title: None,
            project_id: None,
            description: None,
            parent_task_id: None,
            assignee_id: None,
            done: None,
            due_date: None,
            creator_id: None,
            add_time: None,
            update_time: None,
            marked_as_done_time: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Done {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
}

impl Default for Done {
    fn default() -> Done {
        Self::Variant0
    }
}

